services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local